### PR TITLE
Add function and class to convert cfg formatted glycans to IUPAC condensed format

### PR DESCRIPTION
**Pull request by klarich**
Added function to glycowork/motif/tokenization.py, added tests to build/lib/tests/test_tokenization.py

### CODE REVIEW

**Comment by Bribak** [comment]
Thanks so much!:-)

Currently, the test would fail, as we'd not consider the 'GlcNAcGly' a modified monosaccharide (we'd trim the linker away). Gly modifications are possible, but only with location indication (e.g., 6Gly or OGly if unknown) and if a user would want to parse this one they'd likely have to provide their own lib to glycan_to_nxGraph (I doubt that GlcNAc1Gly would be in our lib atm)
Also, we probably don't have Neu5Ac9NAc in our lib (I'm not convinced that this isn't a CFG typo or similar, as the "physiological" form would be Neu5Ac9Ac)

[As you probably noticed, our test files are pretty legacy (which is already a euphemism); we have and/or will deprecate them and transition to double-use our documentation as tests. Running nbdev_prepare in the local repo will simulate that test locally, by executing all cells in the notebooks comprising the documentation, and make noise if anything doesn't work as expected. But that's just fyi, doesn't matter for the PR, I'll merge it as is and modify later]

[Also fyi: the likely long-term perspective is that we'll migrate bits and pieces of this parser into canonicalize_iupac]

**Comment by kklarich** [comment]
Yeah no problem! Glad to finally get this done. Do I need to do anything to get the docs updated? I noticed it said "Docs are automatically created from the notebooks in the nbs folder." in the contributing.md file. 

Re: tests, that's pretty cool, nbdev is new to me. 

Yeah, I noticed that there was quite a bit of overlap between canonicalize IUPAC and the functions I wrote, but wasn't quite sure how to combine them (though could probably figure it out with a bit more time).

**Comment by klarich** [comment]
Yeah no problem! Good to finally get this done. Do I need to do anything to get the docs update? I noticed it said in the CONTRIBUTING.md file that the docs would automatically get updated by nbdev. 

re: tests, that's pretty cool that nbdev can do that. I haven't used nbdev before. 

And yes I noticed there is a bit of overlap between canonicalize IUPAC and the functions I wrote but wasn't quite sure how to combine them.

**Comment by Bribak** [comment]
The docs are generated from the .ipynb files, so in this case it would stem from 03_motif. In there, the functions are called via show_docs & many have some kind of minimal usage example thereafter. The more extensive usage examples would be in workflows in 00_core or 05_examples

In principle, you can thus add newly added functions into the correpondings docs with the PR; in practice I tend to only really polish the docs directly prior to the version bump (as the web-version of the docs is built from the master branch anyways)

**Comment by klarich** [comment]
Ah, got it, I'll remember to do that next time!

**Pull request merged**
